### ISSUE TITLE
All cases are evaluated.

### ISSUE THREAD

**Issue by Asday** [AlexSergey/react-switch-case#3]
I'm not sure if this is something inherent to React and not fixable by you, but it's causing me an issue.

[SSCCE](https://codesandbox.io/embed/dreamy-kilby-5bfc7).

I'm using a `<Switch />` to render different things based on which props I have.  If I have `a`, but not `b`, I render something that depends on `a`, etc.

The problem I'm having is that all my `<Case />`s are being evaluated, so something that calls `b.foo()` in an unrendered `<Case />` is crashing my app.  I've demonstrated that in the SSCCE above with a simple error being thrown.  Given the `<Case />` isn't rendered, I don't think it should be evaluated.

**Comment by AlexSergey** [comment]
I think you need to wrap it in anonymous self-invoking function, something like that -
```jsx
<Case value={true}>
    {() => <span>{err()}</span>)()}
</Case>
```
Because all you components in the render will be call and trigger error in this case

**Comment by Asday** [comment]
Updated the [SSCCE](https://codesandbox.io/embed/dreamy-kilby-5bfc7) with that suggestion, but it unfortunately doesn't work.

**Comment by AlexSergey** [comment]
Try this one

const Wrap = props => props.children();

<Case value={true}>
    <Wrap>
        {() => <span>{err()}</span>}
    </Wrap>
</Case>

**Comment by Asday** [comment]
It does indeed, thank you.
